mysql:
  user : douyin
  password : a123456
  host : 1.12.244.193
  port : 3306
  dbname : douyin

oss :
  server :
    ip: 192.168.50.87
    port: 8080

aliyun:
  vod:
    file:
     keyid:
     keysecret: